
//shared
global using Microsoft.Extensions.DependencyInjection;

//publico objetivos
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Presenters.PublicoObjetivos;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Ports.PublicoObjetivos.Create;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Ports.PublicoObjetivos.Select;
global using Sentir_Creativo_Backend.PublicoObjetivos.Presenters.PublicoObjetivos;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.ViewModels;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Ports.PublicoObjetivos.Update;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Ports.PublicoObjetivos.Delete;