
//shared
global using FluentValidation;
global using Microsoft.Extensions.DependencyInjection;
global using Sentir_Creativo_Backend.SharedKernel.Entities.Exceptions;

//publicos objetivos
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Dtos;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Ports.PublicoObjetivos.Create;
global using Sentir_Creativo_Backend.SharedKernel.Entities.Contracts;
global using Sentir_Creativo_Backend.PublicoObjetivos.Entities.POCOEntities;
global using Sentir_Creativo_Backend.SharedKernel.UseCases.Validators;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Ports.PublicoObjetivos.Select;
global using Sentir_Creativo_Backend.PublicoObjetivos.UseCases.PublicoObjetivos.Create;
global using Sentir_Creativo_Backend.PublicoObjetivos.UseCases.PublicoObjetivos.Select;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Ports.PublicoObjetivos.Update;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Specifications.PublicoObjetivos;
global using Sentir_Creativo_Backend.PublicoObjetivos.UseCases.PublicoObjetivos.Update;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Ports.PublicoObjetivos.Delete;
global using Sentir_Creativo_Backend.PublicoObjetivos.UseCases.PublicoObjetivos.Delete;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Ports.PublicoObjetivos.GetAll;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.ViewModels.PublicoObjetivos;
global using Sentir_Creativo_Backend.PublicoObjetivos.UseCases.PublicoObjetivos.GetAll;
global using Sentir_Creativo_Backend.PublicoObjectivos.BusinessObject.Contracts.Ports.PublicoObjetivos.GetById;
global using Sentir_Creativo_Backend.PublicoObjetivos.UseCases.PublicoObjetivos.GetById;