global using Sentir_Creativo_Backend.Servicios.BusinessObject.Contracts.Controllers.Ocacions;
global using Sentir_Creativo_Backend.Servicios.BusinessObject.Contracts.Ports.Ocacions.Create;
global using Sentir_Creativo_Backend.Servicios.BusinessObject.Contracts.Presenters.Ocacions;
global using Sentir_Creativo_Backend.Servicios.BusinessObject.Dtos.Ocacions;
global using Sentir_Creativo_Backend.Servicios.BusinessObject.Contracts.Ports.Ocacions.Update;
global using Sentir_Creativo_Backend.Servicios.BusinessObject.Contracts.Ports.Ocacions.Delete;
global using Sentir_Creativo_Backend.Servicios.BusinessObject.Contracts.Presenters.Ocaciones;