global using Sentir_Creativo_Backend.Servicios.BusinessObject.Dtos.Ocacions;
global using Sentir_Creativo_Backend.Servicios.BusinessObject.ViewModels.Formatos;
global using Sentir_Creativo_Backend.Servicios.BusinessObject.Contracts.Ports.EstadosServicios.Select;
global using Sentir_Creativo_Backend.Servicios.BusinessObject.ViewModels.EstadoServicios;
global using Sentir_Creativo_Backend.Servicios.BusinessObject.Contracts.Ports.Formatos.Select;
global using Sentir_Creativo_Backend.Servicios.Entities.POCOEntities;
global using Sentir_Creativo_Backend.SharedKernel.Entities.Specifications;